apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  namespace:
      name: calculator-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
    spec:
      containers:
      - name: calculator-app
        image: my-app-image:latest
        ports:
        - containerPort: 7000

---
apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
  namespace:
      name: calculator-app 
spec:
  selector:
    app: calculator-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7000
  type: NodePort

  
